# .github/workflows/deploy.yml
name: Deploy Quasar SPA to GitHub Pages

on:
  push:
    branches: [ "cicd" ] # <== แก้ไขจาก "master" เป็น "cicd"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # อนุญาตให้ Action เขียนข้อมูลลง repo (เพื่อสร้าง branch gh-pages)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: yarn quasar build
        env:
          BASE_URL: /67041101348-Parama-Taweeketkit/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # ใช้ Token อัตโนมัติของ GitHub
          publish_dir: dist/spa # โฟลเดอร์ที่ได้จากการ build